### ISSUE TITLE
Some members have incorrect class field

### ISSUE THREAD

**Issue by ROODAY** [BUUPE/BUUPE.github.io#85]
Some people on the [members page](https://upe.bu.edu/members) are in the wrong class, e.g. Alpha class has a lot of people who aren't in it (actual class was something like 6-8 people). Will need to go through data in firebase and fix (use the member masterlist).

Also we need to fix the member masterlist, as currently class information is lost for alumni. Can we revert to an older version and keep alumni in the same sheet as active members and just use the status column to indicate alumni? Moving to a new sheet and removing class will make record keeping difficult.

**Comment by ROODAY** [comment]
@vitorvicente do we have an admin page where we could easily change this? Perhaps it could copy the manage users in Inquistor? Or better yet, perhaps managing users/roles should be functionality of the main website and we can move those admin pages to this codebase later.

**Comment by vitorvicente** [comment]
There is a panel but it's restricted to EBoard, this was prior to the admin role

**Comment by ROODAY** [comment]
Ok as long as there's an easy way to modify user data that's fine, permissions can be changed later to allow admins if needed.

**Comment by vitorvicente** [comment]
This should be fixed now, I have revised every Alumn to make sure they are correctly assigned their class, this also brings to light that the way we are currently storing profile pictures really is inefficient, since if we move their classes, we need to move their profile pictures...

Making an issue to refractor ProfileIMGs
